// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShortUrl struct {
	ID        int64
	Slug      string
	TargetUrl string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Visit struct {
	ID         int64
	ShortUrlID int64
	OccurredAt pgtype.Timestamptz
	UserAgent  pgtype.Text
}
