// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"
)

type Querier interface {
	CreateShortURL(ctx context.Context, arg CreateShortURLParams) (ShortUrl, error)
	GetShortURL(ctx context.Context, id int64) (ShortUrl, error)
	GetShortURLBySlug(ctx context.Context, slug string) (ShortUrl, error)
}

var _ Querier = (*Queries)(nil)
