// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: visit.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVisit = `-- name: CreateVisit :one
INSERT INTO visit (short_url_id, user_agent, occurred_at)
SELECT s.id, $2, $3
FROM short_url as s
WHERE s.slug = $1
RETURNING id, short_url_id, occurred_at, user_agent
`

type CreateVisitParams struct {
	Slug       string
	UserAgent  pgtype.Text
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (Visit, error) {
	row := q.db.QueryRow(ctx, createVisit, arg.Slug, arg.UserAgent, arg.OccurredAt)
	var i Visit
	err := row.Scan(
		&i.ID,
		&i.ShortUrlID,
		&i.OccurredAt,
		&i.UserAgent,
	)
	return i, err
}
